#!/bin/sh
# Read ../config.ini and write docker/.env so that docker-compose can interpolate
# POSTGRES_*, REDIS_*, and APP_PORT without exposing config.ini values to the
# repository.
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG="${SCRIPT_DIR}/../config.ini"
ENV_FILE="${SCRIPT_DIR}/.env"

if [ ! -f "${CONFIG}" ]; then
    echo "Missing config.ini at ${CONFIG}" >&2
    exit 1
fi

awk -v out="${ENV_FILE}" '
function trim(s)        { sub(/^[ \t]+/, "", s); sub(/[ \t]+$/, "", s); return s }
function strip(s, c)    { gsub(c, "", s); return s }

BEGIN {
    section = ""
    print "# Generated by docker/sync_compose_from_config.sh - do not edit by hand" > out
}

/^[ \t]*#/ || /^[ \t]*$/ { next }

/^\[.*\]/ {
    section = $0
    sub(/^\[/, "", section)
    sub(/\][ \t]*$/, "", section)
    next
}

/=/ {
    eq = index($0, "=")
    key = trim(substr($0, 1, eq - 1))
    val = trim(substr($0, eq + 1))

    if (section == "POSTGRES") {
        if (key == "DATABASE_NAME") printf "POSTGRES_DB=%s\n", val >> out
        else if (key == "USERNAME") printf "POSTGRES_USER=%s\n", val >> out
        else if (key == "PASSWORD") printf "POSTGRES_PASSWORD=%s\n", val >> out
        else if (key == "PORT")     printf "POSTGRES_PORT=%s\n", val >> out
    }
    else if (section == "REDIS") {
        if (key == "PORT")          printf "REDIS_PORT=%s\n", val >> out
        else if (key == "PASSWORD") printf "REDIS_PASSWORD=%s\n", val >> out
        else if (key == "DB")       printf "REDIS_DB=%s\n", val >> out
    }
    else if (section == "GRANIAN") {
        if (key == "PORT")    printf "APP_PORT=%s\n", val >> out
        else if (key == "HOST") printf "APP_HOST=%s\n", val >> out
        else if (key == "WORKERS") printf "GRANIAN_WORKERS=%s\n", val >> out
        else if (key == "LOOP")    printf "GRANIAN_LOOP=%s\n", val >> out
        else if (key == "HTTP")    printf "GRANIAN_HTTP=%s\n", val >> out
    }
}
' "${CONFIG}"

# Sanity check: require Redis password to be set when running production stack.
if ! grep -q '^REDIS_PASSWORD=..*' "${ENV_FILE}"; then
    echo "ERROR: [REDIS] PASSWORD must be non-empty in config.ini for the production stack" >&2
    exit 2
fi

if ! grep -q '^REDIS_PORT=..*' "${ENV_FILE}"; then
    echo "ERROR: [REDIS] PORT must be set in config.ini" >&2
    exit 3
fi

if ! grep -q '^APP_PORT=..*' "${ENV_FILE}"; then
    echo "ERROR: [GRANIAN] PORT must be set in config.ini" >&2
    exit 4
fi

echo "Wrote ${ENV_FILE}"
